# -*- coding: utf-8 -*-
"""list type.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LpOez6Kccou6XLVLlsDGucsXSR6SW5Xr
"""



"""# loops in list"""

party_food = [
    "Momo",
    "Paneer",
    "Matar paneer",
    "fruits",
    "Pizza",
    "cod drinks",
    "Chocolates"
]

len(party_food)

for index in range (len(party_food)):
  print(index, party_food[index])

for item in party_food:
  print(item)

for index, item in enumerate(party_food):
  print(index, item)

"""# Mean 
$\bar x = \frac{\sumx $
"""

nums = [22, 55, 66, 8, 2]

total = 0
for item in nums:
  total = total + item
n = len(nums)
mean = total/n
print(mean)





